version: '3.8'

services:
  xkids-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: xkids-learning-center:latest
    container_name: xkids-learning-center
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "com.exrienz.app=xkids-learning-center"
      - "com.exrienz.description=Educational apps for children"
      - "com.exrienz.version=1.0.0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - xkids-network

  # Optional: Add SSL/TLS termination with Traefik
  traefik:
    image: traefik:v2.10
    container_name: xkids-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik:ro
      - ./ssl-certs:/ssl-certs:ro
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=muzaffar.mohamed@example.com
      - --certificatesresolvers.myresolver.acme.storage=/ssl-certs/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - xkids-network
    profiles:
      - production

  # Production service with Traefik integration
  xkids-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: xkids-learning-center:latest
    container_name: xkids-learning-center-prod
    restart: unless-stopped
    environment:
      - NGINX_HOST=xkids.exrienz.com
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xkids.rule=Host(`xkids.exrienz.com`)"
      - "traefik.http.routers.xkids.entrypoints=websecure"
      - "traefik.http.routers.xkids.tls.certresolver=myresolver"
      - "traefik.http.routers.xkids-redirect.rule=Host(`xkids.exrienz.com`)"
      - "traefik.http.routers.xkids-redirect.entrypoints=web"
      - "traefik.http.routers.xkids-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "com.exrienz.app=xkids-learning-center"
      - "com.exrienz.environment=production"
    networks:
      - xkids-network
    profiles:
      - production

networks:
  xkids-network:
    driver: bridge
    labels:
      - "com.exrienz.network=xkids-learning-center"

volumes:
  ssl-certs:
    driver: local
    labels:
      - "com.exrienz.volume=ssl-certificates"